apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nodejs-backend-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nodejs-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-backend-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodejs-backend-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodejs-backend-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: nodejs-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: nodejs-backend-role
  apiGroup: rbac.authorization.k8s.io
